server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_miaosha?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8 #查到的时间+8小时
    date-format: yyyy-MM-dd HH:mm:ss #返回的时间格式
  redis:
    host: 192.168.0.141
    port: 6379
    password: 123456
    database: 0
    timeout: 1000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  rabbitmq:
    host: 192.168.0.141
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: CORRELATED
    virtual-host: /

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO #id自增
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: FULL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mybatis/mapper/*.xml